Repository Mindula-Dilthushan/awesome-github-readme-profiles, pull requests merged in 2022-08, with the labels that each got.

#14 update-new-readme-links
  README.md
Labels: feat

#15 Update README.md
  README.md
Labels: enhancement

#18 new-readme-updates
  README.md
Labels: update
